using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// 落下オブジェクト
/// </summary>
public class CS_FallingObj : MonoBehaviour
{
    [SerializeField, Header("生成Effect")]
    private GameObject BreakEffect;
    [SerializeField]
    private GameObject BreakDust;

    /// <summary>
    /// 床と接触したら消滅する
    /// </summary>
    /// <param 衝突物="collision"></param>
    private void OnCollisionEnter(Collision collision)
    {
        //何かと接触したら消す
        Destroy(this.gameObject);

        Vector3 pos = transform.position;
        Instantiate(BreakEffect,pos,Quaternion.identity);
        //Instantiate(BreakDust,pos,Quaternion.identity);

        //プレイヤーと接触したか
        bool HitFloor = collision.gameObject.tag == "Player";
        if (HitFloor)
        {
            //Destroy(this.gameObject);
        }
    }
}
